#
# Automatically generated file. DO NOT MODIFY
#

PRODUCT_SOONG_NAMESPACES += \
    vendor/samsung/universal9830-common

PRODUCT_COPY_FILES += \
    vendor/samsung/universal9830-common/proprietary/system_ext/etc/permissions/com.android.hotwordenrollment.common.util.xml:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/permissions/com.android.hotwordenrollment.common.util.xml \
    vendor/samsung/universal9830-common/proprietary/vendor/etc/eden/gpu/eden_kernel_64.bin:$(TARGET_COPY_OUT_VENDOR)/etc/eden/gpu/eden_kernel_64.bin \
    vendor/samsung/universal9830-common/proprietary/vendor/etc/gnss/gps.cer:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/gps.cer \
    vendor/samsung/universal9830-common/proprietary/vendor/etc/init/android.hardware.drm@1.3-service.widevine.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.drm@1.3-service.widevine.rc \
    vendor/samsung/universal9830-common/proprietary/vendor/etc/init/android.hardware.keymaster@4.0_strongbox-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.keymaster@4.0_strongbox-service.rc \
    vendor/samsung/universal9830-common/proprietary/vendor/etc/init/android.hardware.neuralnetworks@1.3-service.eden-drv.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.neuralnetworks@1.3-service.eden-drv.rc \
    vendor/samsung/universal9830-common/proprietary/vendor/etc/init/vendor.samsung.hardware.gnss@2.1-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.samsung.hardware.gnss@2.1-service.rc \
    vendor/samsung/universal9830-common/proprietary/vendor/etc/init/vendor.samsung_slsi.hardware.eden_runtime@1.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.samsung_slsi.hardware.eden_runtime@1.0-service.rc \
    vendor/samsung/universal9830-common/proprietary/vendor/etc/plmn_delta.bin:$(TARGET_COPY_OUT_VENDOR)/etc/plmn_delta.bin \
    vendor/samsung/universal9830-common/proprietary/vendor/etc/plmn_delta_attaio.bin:$(TARGET_COPY_OUT_VENDOR)/etc/plmn_delta_attaio.bin \
    vendor/samsung/universal9830-common/proprietary/vendor/etc/plmn_delta_usagsm.bin:$(TARGET_COPY_OUT_VENDOR)/etc/plmn_delta_usagsm.bin \
    vendor/samsung/universal9830-common/proprietary/vendor/etc/plmn_se13.bin:$(TARGET_COPY_OUT_VENDOR)/etc/plmn_se13.bin \
    vendor/samsung/universal9830-common/proprietary/vendor/etc/sensor/lhd.conf:$(TARGET_COPY_OUT_VENDOR)/etc/sensor/lhd.conf \
    vendor/samsung/universal9830-common/proprietary/vendor/firmware/APSV_AUDIO_SLSI.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/APSV_AUDIO_SLSI.bin \
    vendor/samsung/universal9830-common/proprietary/vendor/firmware/NPU_NFD_P4.7.tflite:$(TARGET_COPY_OUT_VENDOR)/firmware/NPU_NFD_P4.7.tflite \
    vendor/samsung/universal9830-common/proprietary/vendor/firmware/a2dpcom.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/a2dpcom.bin \
    vendor/samsung/universal9830-common/proprietary/vendor/firmware/abox_tplg.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/abox_tplg.bin \
    vendor/samsung/universal9830-common/proprietary/vendor/firmware/abox_tplg.conf:$(TARGET_COPY_OUT_VENDOR)/firmware/abox_tplg.conf \
    vendor/samsung/universal9830-common/proprietary/vendor/firmware/avsyncmix.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/avsyncmix.bin \
    vendor/samsung/universal9830-common/proprietary/vendor/firmware/bayer2rgb.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/bayer2rgb.bin \
    vendor/samsung/universal9830-common/proprietary/vendor/firmware/bayer2yuv.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/bayer2yuv.bin \
    vendor/samsung/universal9830-common/proprietary/vendor/firmware/bidirmic.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/bidirmic.bin \
    vendor/samsung/universal9830-common/proprietary/vendor/firmware/calliope2.dt:$(TARGET_COPY_OUT_VENDOR)/firmware/calliope2.dt \
    vendor/samsung/universal9830-common/proprietary/vendor/firmware/calliope_dram.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/calliope_dram.bin \
    vendor/samsung/universal9830-common/proprietary/vendor/firmware/calliope_dram_2.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/calliope_dram_2.bin \
    vendor/samsung/universal9830-common/proprietary/vendor/firmware/calliope_sram.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/calliope_sram.bin \
    vendor/samsung/universal9830-common/proprietary/vendor/firmware/calliope_sram_2.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/calliope_sram_2.bin \
    vendor/samsung/universal9830-common/proprietary/vendor/firmware/cs35l40-bot-dsp1-spk-prot.wmfw:$(TARGET_COPY_OUT_VENDOR)/firmware/cs35l40-bot-dsp1-spk-prot.wmfw \
    vendor/samsung/universal9830-common/proprietary/vendor/firmware/cs35l40-rcv-dsp1-spk-prot.wmfw:$(TARGET_COPY_OUT_VENDOR)/firmware/cs35l40-rcv-dsp1-spk-prot.wmfw \
    vendor/samsung/universal9830-common/proprietary/vendor/firmware/cs40l20.wmfw:$(TARGET_COPY_OUT_VENDOR)/firmware/cs40l20.wmfw \
    vendor/samsung/universal9830-common/proprietary/vendor/firmware/cs40l25a.wmfw:$(TARGET_COPY_OUT_VENDOR)/firmware/cs40l25a.wmfw \
    vendor/samsung/universal9830-common/proprietary/vendor/firmware/cs40l25a_cal.wmfw:$(TARGET_COPY_OUT_VENDOR)/firmware/cs40l25a_cal.wmfw \
    vendor/samsung/universal9830-common/proprietary/vendor/firmware/cs40l25a_clab.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/cs40l25a_clab.bin \
    vendor/samsung/universal9830-common/proprietary/vendor/firmware/cs40l25a_clab.wmfw:$(TARGET_COPY_OUT_VENDOR)/firmware/cs40l25a_clab.wmfw \
    vendor/samsung/universal9830-common/proprietary/vendor/firmware/cs40l25a_exc.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/cs40l25a_exc.bin \
    vendor/samsung/universal9830-common/proprietary/vendor/firmware/dax_param.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/dax_param.bin \
    vendor/samsung/universal9830-common/proprietary/vendor/firmware/default_configuration.flm.cfg.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/default_configuration.flm.cfg.bin \
    vendor/samsung/universal9830-common/proprietary/vendor/firmware/dsp.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/dsp.bin \
    vendor/samsung/universal9830-common/proprietary/vendor/firmware/dsp_dn.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/dsp_dn.bin \
    vendor/samsung/universal9830-common/proprietary/vendor/firmware/dsp_do.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/dsp_do.bin \
    vendor/samsung/universal9830-common/proprietary/vendor/firmware/dsp_gkt.xml:$(TARGET_COPY_OUT_VENDOR)/firmware/dsp_gkt.xml \
    vendor/samsung/universal9830-common/proprietary/vendor/firmware/dsp_iac_dm.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/dsp_iac_dm.bin \
    vendor/samsung/universal9830-common/proprietary/vendor/firmware/dsp_iac_dm_dn.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/dsp_iac_dm_dn.bin \
    vendor/samsung/universal9830-common/proprietary/vendor/firmware/dsp_iac_dm_do.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/dsp_iac_dm_do.bin \
    vendor/samsung/universal9830-common/proprietary/vendor/firmware/dsp_iac_pm.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/dsp_iac_pm.bin \
    vendor/samsung/universal9830-common/proprietary/vendor/firmware/dsp_iac_pm_dn.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/dsp_iac_pm_dn.bin \
    vendor/samsung/universal9830-common/proprietary/vendor/firmware/dsp_iac_pm_do.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/dsp_iac_pm_do.bin \
    vendor/samsung/universal9830-common/proprietary/vendor/firmware/dsp_ivp_dm.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/dsp_ivp_dm.bin \
    vendor/samsung/universal9830-common/proprietary/vendor/firmware/dsp_ivp_dm_dn.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/dsp_ivp_dm_dn.bin \
    vendor/samsung/universal9830-common/proprietary/vendor/firmware/dsp_ivp_dm_do.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/dsp_ivp_dm_do.bin \
    vendor/samsung/universal9830-common/proprietary/vendor/firmware/dsp_ivp_pm.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/dsp_ivp_pm.bin \
    vendor/samsung/universal9830-common/proprietary/vendor/firmware/dsp_ivp_pm_dn.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/dsp_ivp_pm_dn.bin \
    vendor/samsung/universal9830-common/proprietary/vendor/firmware/dsp_ivp_pm_do.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/dsp_ivp_pm_do.bin \
    vendor/samsung/universal9830-common/proprietary/vendor/firmware/dsp_master.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/dsp_master.bin \
    vendor/samsung/universal9830-common/proprietary/vendor/firmware/dsp_reloc_rules.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/dsp_reloc_rules.bin \
    vendor/samsung/universal9830-common/proprietary/vendor/firmware/fmsb.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/fmsb.bin \
    vendor/samsung/universal9830-common/proprietary/vendor/firmware/gdc.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/gdc.bin \
    vendor/samsung/universal9830-common/proprietary/vendor/firmware/libann.elf:$(TARGET_COPY_OUT_VENDOR)/firmware/libann.elf \
    vendor/samsung/universal9830-common/proprietary/vendor/firmware/libenf.elf:$(TARGET_COPY_OUT_VENDOR)/firmware/libenf.elf \
    vendor/samsung/universal9830-common/proprietary/vendor/firmware/libenf_uv.elf:$(TARGET_COPY_OUT_VENDOR)/firmware/libenf_uv.elf \
    vendor/samsung/universal9830-common/proprietary/vendor/firmware/libivp.elf:$(TARGET_COPY_OUT_VENDOR)/firmware/libivp.elf \
    vendor/samsung/universal9830-common/proprietary/vendor/firmware/liblog.elf:$(TARGET_COPY_OUT_VENDOR)/firmware/liblog.elf \
    vendor/samsung/universal9830-common/proprietary/vendor/firmware/libnn.elf:$(TARGET_COPY_OUT_VENDOR)/firmware/libnn.elf \
    vendor/samsung/universal9830-common/proprietary/vendor/firmware/listenbackeffect.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/listenbackeffect.bin \
    vendor/samsung/universal9830-common/proprietary/vendor/firmware/mfc_fw.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/mfc_fw.bin \
    vendor/samsung/universal9830-common/proprietary/vendor/firmware/rgb2bayer.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/rgb2bayer.bin \
    vendor/samsung/universal9830-common/proprietary/vendor/firmware/sb_ll.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/sb_ll.bin \
    vendor/samsung/universal9830-common/proprietary/vendor/firmware/sb_music.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/sb_music.bin \
    vendor/samsung/universal9830-common/proprietary/vendor/firmware/sb_others.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/sb_others.bin \
    vendor/samsung/universal9830-common/proprietary/vendor/firmware/sv.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/sv.bin \
    vendor/samsung/universal9830-common/proprietary/vendor/firmware/txse2.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/txse2.bin \
    vendor/samsung/universal9830-common/proprietary/vendor/firmware/txse3.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/txse3.bin \
    vendor/samsung/universal9830-common/proprietary/vendor/firmware/usbin.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/usbin.bin \
    vendor/samsung/universal9830-common/proprietary/vendor/firmware/usbout.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/usbout.bin \
    vendor/samsung/universal9830-common/proprietary/vendor/firmware/volumemonitor.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/volumemonitor.bin \
    vendor/samsung/universal9830-common/proprietary/vendor/firmware/yuv2bayer.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/yuv2bayer.bin \
    vendor/samsung/universal9830-common/proprietary/vendor/tee/00000000-0000-0000-0000-000000020081:$(TARGET_COPY_OUT_VENDOR)/tee/00000000-0000-0000-0000-000000020081 \
    vendor/samsung/universal9830-common/proprietary/vendor/tee/00000000-0000-0000-0000-000048444350:$(TARGET_COPY_OUT_VENDOR)/tee/00000000-0000-0000-0000-000048444350 \
    vendor/samsung/universal9830-common/proprietary/vendor/tee/00000000-0000-0000-0000-00575644524d:$(TARGET_COPY_OUT_VENDOR)/tee/00000000-0000-0000-0000-00575644524d \
    vendor/samsung/universal9830-common/proprietary/vendor/tee/00000000-0000-0000-0000-5354494d4552:$(TARGET_COPY_OUT_VENDOR)/tee/00000000-0000-0000-0000-5354494d4552 \
    vendor/samsung/universal9830-common/proprietary/vendor/tee/00000000-0000-0000-0000-564c544b5052:$(TARGET_COPY_OUT_VENDOR)/tee/00000000-0000-0000-0000-564c544b5052 \
    vendor/samsung/universal9830-common/proprietary/vendor/tee/00000000-0000-0000-0000-64756c444152:$(TARGET_COPY_OUT_VENDOR)/tee/00000000-0000-0000-0000-64756c444152 \
    vendor/samsung/universal9830-common/proprietary/vendor/tee/00000000-0000-0000-0000-656e676d6f64:$(TARGET_COPY_OUT_VENDOR)/tee/00000000-0000-0000-0000-656e676d6f64 \
    vendor/samsung/universal9830-common/proprietary/vendor/tee/00000000-0000-0000-0000-6d73745f5441:$(TARGET_COPY_OUT_VENDOR)/tee/00000000-0000-0000-0000-6d73745f5441 \
    vendor/samsung/universal9830-common/proprietary/vendor/tee/driver/00000000-0000-0000-0000-494363447256:$(TARGET_COPY_OUT_VENDOR)/tee/driver/00000000-0000-0000-0000-494363447256 \
    vendor/samsung/universal9830-common/proprietary/vendor/tee/driver/00000000-0000-0000-0000-4d53546d7374:$(TARGET_COPY_OUT_VENDOR)/tee/driver/00000000-0000-0000-0000-4d53546d7374 \
    vendor/samsung/universal9830-common/proprietary/vendor/tee/driver/00000000-0000-0000-0000-564c544b4456:$(TARGET_COPY_OUT_VENDOR)/tee/driver/00000000-0000-0000-0000-564c544b4456 \
    vendor/samsung/universal9830-common/proprietary/vendor/tee/driver/18d9f073-18a5-4ade-9def-875e07f7f293_:$(TARGET_COPY_OUT_VENDOR)/tee/driver/18d9f073-18a5-4ade-9def-875e07f7f293_ \
    vendor/samsung/universal9830-common/proprietary/vendor/tee/ffffffff-0000-0000-0000-000000000030:$(TARGET_COPY_OUT_VENDOR)/tee/ffffffff-0000-0000-0000-000000000030 \
    vendor/samsung/universal9830-common/proprietary/vendor/tee/tui/resolution_common/ID00000100:$(TARGET_COPY_OUT_VENDOR)/tee/tui/resolution_common/ID00000100

PRODUCT_PACKAGES += \
    vendor.samsung.hardware.radio-V1-ndk \
    vendor.samsung.hardware.radio.bridge-V1-ndk \
    libGLES_mali \
    vulkan.mali \
    libSEF.quram \
    libSamsungPostProcessConvertor \
    lib_SoundAlive_SRC384_ver320 \
    lib_soundaliveresampler \
    libbayergdccore \
    libexynoscamera_plugin \
    libsec_semRil \
    libsecnativefeature \
    libsecril-client \
    libsemnativecarrierfeature \
    libprofileparamstorage \
    libsecaudiocoreutils \
    libspatializerparamstorage \
    libwvhidl \
    android.hardware.gnss@2.1-impl \
    flp.default \
    gatekeeper.exynos990 \
    gps.default \
    vendor.samsung.hardware.gnss@2.1-impl \
    libSemDataProps \
    libSemTelephonyProps \
    libcommon \
    libcrane_compiler \
    libeden_model \
    libeden_nn \
    libeden_nn_on_vendor \
    libeden_osal \
    libeden_profiler \
    libeden_rt \
    libeden_rt_stub_vendor.edensdk.samsung \
    libeden_ud_cpu \
    libeden_ud_dsp \
    libeden_ud_gpu \
    libeden_ud_npu \
    libeden_wrapper \
    libeden_wrapper_sdk \
    libeden_xtool \
    libengmode_client \
    libenn_dsp_dal \
    libenn_dsp_fw_graph_parser \
    libenn_dsp_kernels_cpu \
    libexynoscamera_fakefusion \
    libexynoscamera_fakefusion_plugin \
    libexynoscamera_plugin_utils \
    libfloatingfeature \
    libgraphgen_ann_import \
    libgraphgen_ann_nnc \
    libgraphgen_api \
    libgraphgen_export \
    libgraphgen_import \
    libgraphgen_intermediate_process \
    libgraphgen_misc \
    libgraphgen_network \
    libir \
    libkeymaster_helper \
    libnpu_compiler \
    libnpuc_api \
    libnpuc_backend \
    libnpuc_cmdq \
    libnpuc_common \
    libnpuc_controller \
    libnpuc_frontend \
    libnpuc_graph \
    libnpuc_template \
    libril_sem \
    librilutils \
    libsait_npu_compiler \
    libsec-ril \
    libskeymaster4device \
    libvkmanager_vendor \
    libvpl \
    sensors.flicker \
    vendor.samsung.hardware.gnss@2.0 \
    vendor.samsung.hardware.gnss@2.1 \
    vendor.samsung.hardware.radio.bridge@2.0 \
    vendor.samsung.hardware.radio.bridge@2.1 \
    vendor.samsung.hardware.radio.channel@2.0 \
    vendor.samsung.hardware.radio@2.0 \
    vendor.samsung.hardware.radio@2.1 \
    vendor.samsung.hardware.radio@2.2 \
    vendor.samsung_slsi.hardware.eden_runtime@1.0-impl \
    vendor.samsung_slsi.hardware.eden_runtime@1.0 \
    com.android.hotwordenrollment.common.util \
    manifest_android.hardware.drm@1.3-service.widevine.xml \
    android.hardware.drm@1.3-service.widevine \
    android.hardware.keymaster@4.0_strongbox-service \
    android.hardware.neuralnetworks@1.3-service.eden-drv \
    gps \
    lhd \
    rild \
    vendor.samsung.hardware.gnss@2.1-service \
    vendor.samsung_slsi.hardware.eden_runtime@1.0-service \
    tzts_daemon

PRODUCT_PACKAGES += \
    vendor_lib_libOpenCL_so \
    vendor_lib_libOpenCL_so_1 \
    vendor_lib_libOpenCL_so_1_1 \
    vendor_lib64_libOpenCL_so \
    vendor_lib64_libOpenCL_so_1 \
    vendor_lib64_libOpenCL_so_1_1
